# Generated by Django 3.2.18 on 2023-07-11 00:19

from django.db import migrations, models
import iolApi.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('dhis2_host', models.CharField(max_length=255, unique=True)),
                ('dhis2_port', models.CharField(max_length=255)),
                ('dhis2_username', models.CharField(max_length=255)),
                ('dhis2_password', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'dispatcher_config',
            },
        ),
        migrations.CreateModel(
            name='IOLHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('port', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=10240, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'IOL Server Host',
                'db_table': 'iol_host',
            },
        ),
        migrations.CreateModel(
            name='JsonMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_url', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=10240, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'json_mapper',
            },
        ),
        migrations.CreateModel(
            name='MetadataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_config_file', models.FileField(blank=True, max_length=5000, null=True, upload_to=iolApi.models._upload_metadata_config_file)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'metadata_upload',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('admin_email', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('port', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'notification_config',
            },
        ),
    ]
